version: '3.7'
services:
  tracker-database:
    image: mysql:8.0.15
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=${TRACKER_DB_NAME}
      - MYSQL_USER=${TRACKER_DB_USER_NAME}
      - MYSQL_PASSWORD=${TRACKER_DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${TRACKER_DB_PASSWORD}
    volumes:
      - /data/tracker-database

  tracker:
    build:
      context: .
    image: tracker:1.0.0
    ports:
      - 8080:8080
    depends_on:
      - tracker-database
    environment:
      - TRACKER_DB_URL=${TRACKER_DB_URL}
      - TRACKER_DB_PORT=${TRACKER_DB_PORT}
      - TRACKER_DB_NAME=${TRACKER_DB_NAME}
      - TRACKER_DB_USER_NAME=${TRACKER_DB_USER_NAME}
      - TRACKER_DB_PASSWORD=${TRACKER_DB_PASSWORD}
      - TRACKER_ACTIVE_PROFILES=${TRACKER_ACTIVE_PROFILES}
    volumes:
      - /data/tracker