version: '3.7'
services:
  tracker-database:
    image: mysql:8.0.15
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=tracker
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - /data/tracker-database

  adminer:
    image: adminer
    restart: always
    ports:
      - 8100:8080


  tracker:
    image: tracker:1.0.0
    ports:
      - 8080:8080
    depends_on:
      - tracker-database
    environment:
      - TRACKER_DB_URL=tracker-database
      - TRACKER_DB_PORT=3306
      - TRACKER_DB_NAME=tracker
      - TRACKER_DB_USER_NAME=dbuser
      - TRACKER_DB_PASSWORD=password
      - TRACKER_ACTIVE_PROFILES=production
    volumes:
      - /data/tracker